### ISSUE TITLE
Issue with VAT values

### ISSUE THREAD

**Issue by GonzoTBA** [mathialo/simpleinvoice#1]
Hi. Thank you for the template!

I am having an issue adding the VAT for new items.
This works alright: 
\additem{Concepto del servicio}{100,00 \euro}

But this doesn't:
\additem{Concepto del servicio}{100,00 \euro}{21}{121,00 \euro}

The third and fourth arguments are somehow printed to the left of the Receiver Name, pushing it towards right.

Can you please lend me a hand?

**Comment by mathialo** [comment]
Hi (and sorry for the late reply).

I am not able to reproduce this issue (using the `eurosym` package for the `\euro` command). Can you share a full tex file that produces the error?

**Comment by GonzoTBA** [comment]
Thank you for the reply. It is ok, I am using Google docs for my invoices now :-)
